[package]
name = "maria-static"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maria = "0.8.1"
tokio = "1.32.0"
